RK1
java-park-mail-ru/strategy-09-2016 pull request #1
Opened 2016-10-03 16:20 UTC by VictorKamyshin

Описание API
https://sample-home-task-2.herokuapp.com/api/
В дополнение к нему есть два вспомогательных пути
/hello - сообщает, авторизован ли в данный момент пользователь
/exit - сбрасывает авторизацию у текущего пользователя

2016-10-03 22:43 UTC, KSolovyev commented
А авторизация и регистрация где? Почему не добавили в спецификацию?

2016-10-03 22:55 UTC, VictorKamyshin commented
Я очень извиняюсь. Я перепутал ссылки на задеплоиный фронт. Вот правильная
https://techno-frontend-home-task-2.herokuapp.com/api/

2016-10-03 23:14 UTC, KSolovyev commented
Спека норм, только если вы собираетесь еще какие-то доп методы использовать, то добавьте   их туда. Кстати на мой взгляд нормально если вы добавите в спеку какие-то методы для себя, но решать вашей команде.
Еще одна просьба: добавьте в спеку, что это application/json и по возможности пример данных типа {"name":"Vasya", "password":"1234"}

2016-10-03 23:16 UTC, VictorKamyshin commented
В спеке сказано, что в теле сообщения передаются те или иные параметры. Или надо где-то указать, что формат передачи данных это именно application/json?
Хорошо, мы посмотрим, как через swagger добавлять примеры.

2016-10-04 21:59 UTC, KSolovyev requested changes

2016-10-04 21:59 UTC, KSolovyev commented on .gitignore
> +# Mongo Explorer plugin:
убираем, нет у нас его

2016-10-04 21:59 UTC, KSolovyev commented on .gitignore
> +## File-based project format:
этого тоже нет

2016-10-04 21:59 UTC, KSolovyev commented on .gitignore
> +# Mobile Tools for Java (J2ME)
j2me тем более

2016-10-04 21:59 UTC, KSolovyev commented on src/main/java/ru/mail/park/Application.java
> +                registry.addMapping("/**").allowedOrigins("*");
Если в апи есть экзотические методы, типа DELETE, то надо добавить в список разрешенных в  CORS методов

2016-10-04 21:59 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +            return ResponseEntity.status(HttpStatus.FORBIDDEN).body("Вы уже авторизированы");
~~id сессии это, фактически, кука. Вы запрещаете авторизироваться второй раз. Т.е. если я залогинился дома, то с работы мне уже зайти не удастся(~~
Это у вас оказывается функция регистрации. Почему она называется login? Вы меня совсем запутали.

2016-10-04 21:59 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body("Один из параметров пуст");
Передавать текст сообщений в api - это плохая привычка. Если вы вдруг решите сделать мультиязычное приложение, то локализацию, вместо того, чтобы хранить ее на клиенте, придется раскорячить и на клиент и на сервер. Лучше сразу делать ее на клиенте, а с сервера слать код ошибки или ключ сообщения в клиентской локализации

2016-10-04 21:59 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +                    sessionService.removeUser(sessionId);
А зачем вы это делаете?

2016-10-04 21:59 UTC, KSolovyev commented on src/main/java/ru/mail/park/model/UserProfile.java
> +    private static final AtomicLong IDGENERATOR = new AtomicLong(0);
статические поля должны быть сверху класса, перед обычными

2016-10-04 21:59 UTC, KSolovyev commented on src/main/java/ru/mail/park/services/SessionService.java
> + * ДЗ: реализовать класс, который по соответствующему id сессии будет отдавать пользователей(т.е. реализовать авторизацию по сессии)
коммент надо убрать

2016-10-04 21:59 UTC, KSolovyev commented on src/main/resources/banner.txt
> +
Вы можете, конечно, оставить этот баннер, но это как-то не круто...

2016-10-04 21:59 UTC, KSolovyev commented on tp_java_new.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Этот файл в репозитории не нужен, если вы уже импортировали профиль инспекций

2016-10-04 21:59 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +        } else {
else не нужен, без него читается легче

2016-10-04 21:59 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +        } else {
аналогично, else не нужен

2016-10-04 22:04 UTC, VictorKamyshin commented on src/main/java/ru/mail/park/Application.java
> +                registry.addMapping("/**").allowedOrigins("*");
То есть, если у нас их пока нет, то исправлять здесь ничего не надо?

2016-10-04 22:07 UTC, VictorKamyshin commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body("Один из параметров пуст");
Понятно. Расшифровку ключей ошибок надо включить в API?

2016-10-04 22:12 UTC, VictorKamyshin commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +                    sessionService.removeUser(sessionId);
Если к нам пришел пользователь и хочет залогиниться, но у него уже установлена сессионая кука, соответствующая другому логину (например, у одного человека два аккаунта), то мы сбрасываем авторизацию старого аккаунта и запоминаем, что авторизирован новый. Такой была задумка.

2016-10-04 22:13 UTC, VictorKamyshin commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +            return ResponseEntity.status(HttpStatus.FORBIDDEN).body("Вы уже авторизированы");
Извиняюсь. Я забыл сменить название функции.

2016-10-04 23:07 UTC, KSolovyev commented on src/main/java/ru/mail/park/Application.java
> +                registry.addMapping("/**").allowedOrigins("*");
да, можно не добавлять. Просто такие ошибки,если они есть, вы поймаете только после деплоя

2016-10-04 23:09 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +                    sessionService.removeUser(sessionId);
как вы думаете, что будет если вы в карту положите что-нибудь, а в этой карте по этому ключу уже лежало что-то другое?

2016-10-04 23:14 UTC, VictorKamyshin commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +                    sessionService.removeUser(sessionId);
Старое значение будет изменено автоматически? Или произойдет ошибка.

2016-10-04 23:18 UTC, VictorKamyshin commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +                    sessionService.removeUser(sessionId);
Ошибок не происходит. Сейчас уберу лишнюю проверку.

2016-10-05 17:14 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +                    sessionService.removeUser(sessionId);
да, вы, фактически, просто замените значение

2016-10-05 17:17 UTC, KSolovyev requested changes

2016-10-05 17:17 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body("reg_1");
надо придумать осмысленное название. Пусть оно и будет немного длинным

2016-10-05 17:18 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body("Один из параметров пуст");
Нет, но должно быть понятно что случилось

2016-10-07 00:06 UTC, VictorKamyshin commented
Добавили ответы в формате JSON.

2016-10-07 08:43 UTC, KSolovyev approved these changes

2016-10-07 08:43 UTC, merged