RK3 MathCore
java-park-mail-ru/strategy-09-2016 pull request #3
Opened 2016-11-17 15:11 UTC by VictorKamyshin

2016-12-01 20:44 UTC, d-frolov requested changes

2016-12-01 20:44 UTC, d-frolov commented on pom.xml
> +			<version>15.0</version>
возьмите лучше 13.0  версию. 15-я по другому выставляет порядок NotNull . ИМХО читабельнее -как в 13

2016-12-01 20:44 UTC, d-frolov commented on src/main/java/ru/mail/park/mechanics/GameContent.java
> +        if(activePlayerId!=(playerId)){
никогда в  Java не сравнивайте объекты через ==, только equals!

в данном выражении вы сравниваете не сами объекты, а ссылки на них!

2016-12-02 14:07 UTC, KSolovyev commented on pom.xml
> +			<version>15.0</version>
можно в настройках поставить, чтобы она этого не делала

2016-12-02 14:15 UTC, VictorKamyshin commented on src/main/java/ru/mail/park/mechanics/GameContent.java
> +        if(activePlayerId!=(playerId)){
Окей, исправил.

2016-12-13 17:15 UTC, KSolovyev commented
Просочились изменения 4 РК

2016-12-13 17:15 UTC, closed without merging

2016-12-13 17:16 UTC, KSolovyev commented
ждем пул-реквест из отдельной ветки