Rk3
java-park-mail-ru/strategy-09-2016 pull request #4
Opened 2016-12-13 17:27 UTC by VictorKamyshin

2016-12-13 19:23 UTC, KSolovyev requested changes
Во-первых избавьтесь от комментариев. Код должен быть понятен без них. И закомментированный код уберите. Если нужно в консольку писать, что именно делает ваша программа, то используете logger.trace и logger.debug - их всегда можно легко включить / выключить

2016-12-13 19:39 UTC, KSolovyev requested changes
Вы можете тестировать механику до того как фронт вас догонит. Для этого надо написать функциональные тесты каждый из которых будет представлять из себя маленькую партию или кусок маленькой партии. Например: 
-Создаем нескольких пользователей
-Добавляем их в очередь
-Смотрим, что создалась сессия и запустилась игра
-Перемещаем фигурки, корабли, смотрим, что они и вправду переместились
и тд

2016-12-13 19:39 UTC, KSolovyev commented on src/main/java/ru/mail/park/websocket/TestMessage.java
> +public class TestMessage { //отладочное сообщение, которое получено от юзера
Тестовые куски должны быть в тестах. Отсюда надо убрать. И Handler тоже

2016-12-13 20:56 UTC, KSolovyev requested changes

2016-12-13 20:56 UTC, KSolovyev commented on src/main/java/ru/mail/park/mechanics/GameContent.java
> +    public String getMap(){
Зачем вы сериализуете сообщение по частям? Давайте сериализовать его, когда уже соберем полное сообщение

2016-12-13 20:56 UTC, KSolovyev commented on src/main/java/ru/mail/park/mechanics/GameSession.java
> +public class GameSession {
У вас есть два класса, которые по идее делают одно и тоже: GameSession и GameContent и соответственно два сервиса GameSessionService и GameProgressService. Я думаю стоит избавится от GameSessionService - он похоже у вас лишний

2016-12-13 20:56 UTC, KSolovyev commented on src/main/java/ru/mail/park/mechanics/internal/GameProgressService.java
> +        final Integer x = cellIndex%13;
что такое это загадочное "13"??

2016-12-13 20:56 UTC, KSolovyev commented on src/main/java/ru/mail/park/mechanics/game/CoordPair.java
> +    private Integer x;
`private final int x`

2016-12-13 20:56 UTC, KSolovyev commented on src/main/java/ru/mail/park/mechanics/internal/GameProgressService.java
> +                testMessage.setMyMessage("Такой ход невозможен. Скорее всего, вы ошиблись в выборе клетки");
Вот это нужно вынести в отдельный сервис, который будет отсылать текстовое сообщение пользователю. А вообще в таких случаях можно кидать исключение, ведь рассинхрон явно исключительная ситуация и дальше продолжать обработку хода мы не собираемся

2016-12-13 20:56 UTC, KSolovyev commented on src/main/java/ru/mail/park/mechanics/internal/GameProgressService.java
> +            e.printStackTrace();
переписать на logger

2016-12-13 20:56 UTC, KSolovyev commented on src/main/java/ru/mail/park/mechanics/game/GameBoard.java
> +        private List<MovementResult> movePirat(Movement piratMove){
тут вам явно не хватит заложенных архитектурных возможностей на реализацию всей механики. Первое, что нужно сделать - это возможность легко расширять последствия хода. Результатом может быть: отправка пирата на корабль, перемещение пирата, пленение; если он в джунглях, то просто заполнение прогресс бара и тд. Результаты хода, должны варьироваться, а это признак того, что на основании MovementResult следует построить иерархию кассов. Каждый такой объект будет представлять собой элементарный результат хода. Цепочка MovementResult будет результатом действия игрока. Для того, чтобы их было видно на фронте, надо добавить в базовый класс поле enum resultType, которое тоже будет сериализоваться. 
Выглядеть будет примерно так:
```
public class MoveResult extends AbstractResult {

public MoveResult(long pirateId, Cell moveTo) {
super(ResultType.Move);
...
}
```

Далее, чтобы не умереть в этой функции от объема кода и кровавых слез, нужно дать клеткам возможность воздействовать на игровой процесс. Т.е. не нужно заставлять клетку делать действие `boardMap[starterX][starterY].piratLeave(piratMove.getPiratId())`
Нужно саму операцию `List<MovementResults> move(long pirateId, Cell fromCell, Cell toCell, @Out List<MovementResults> results)` вынести в отдельный метод(можно в отдельный класс) и давать ему делать свое дело. Идея в том, что каждая Cell будет сама заполнять массивчик results и вообще делать всю механическую работу. В методе `move` должны быть какие-то действия, которые общие для всех клеток. Например:
```
List<MovementResults> move(long pirateId, Cell fromCell, Cell toCell, @Out List<MovementResults> results) {
        //Возможно проверка "можно ли вообще совершить ход?"
        //....
        if (!fromCell.beforeMoveOut(pirateId, fromCell, toCell, results))
            return results;
        if (!fromCell.moveOut(pirateId, fromCell, toCell, results)) 
            return results;
        return toCell.moveIn(pirateId, fromCell, toCell, results);
    }
```
Тогда, например, если вы входите в клетку со стрелкой, то она на методе moveIn должна позвать метод board.move(pirateId, this, this.pointerTo, results); - автоматически переместив пирата дальше.

Обратите внимание, что в этом случае сложность конструирования объектов-клеток увеличивается. Им потребуются гейм-механические зависимости на доску, игроков и тд, но это, я думаю вы решите. Можно Сделать специальный объект CellFactory, который будет скрывать сложность конструирования и облегчит вам тестирование, но это уже на ваше усмотрение.

Кстати можно от results совсем отказаться и в конце хода посылать стейт всей игры. Возможно так будет проще

2016-12-13 21:01 UTC, KSolovyev requested changes

2016-12-13 21:01 UTC, KSolovyev commented on src/main/java/ru/mail/park/mechanics/requests/GetPingMessage.java
> +public class GetPingMessage { //пинг от юзера
не нужно

2016-12-13 21:27 UTC, VictorKamyshin commented on src/main/java/ru/mail/park/websocket/TestMessage.java
> +public class TestMessage { //отладочное сообщение, которое получено от юзера
Если сейчас фронт и бэк идут ровно, то можно ли проводить тесты уже с использованием фронта?
Если пытаться разыграть тестовую партию - значит, нам придется собирать какой-то заранее заданный вариант поля и по нему двигать фишки. И, получится, что тестируется что-то, что мы сделали ради тестов, раз ве нет?

2016-12-13 21:29 UTC, VictorKamyshin commented on src/main/java/ru/mail/park/mechanics/internal/GameProgressService.java
> +                testMessage.setMyMessage("Такой ход невозможен. Скорее всего, вы ошиблись в выборе клетки");
Сервис, который занимается отправкой сообщений пользователю я уже добавил, когда готовился к четвертому рк. Но он сделан под систему сообщений и просто так перенести его в ветку без этой системы может не получиться.

2016-12-13 21:30 UTC, VictorKamyshin commented on src/main/java/ru/mail/park/mechanics/internal/GameProgressService.java
> +        final Integer x = cellIndex%13;
Ширина/длинна игрового поля в клетках. Наверное, надо сделать его как общедоступную константу класса игрового поля.

2016-12-13 21:32 UTC, KSolovyev commented on src/main/java/ru/mail/park/websocket/TestMessage.java
> +public class TestMessage { //отладочное сообщение, которое получено от юзера
тесты нужны. И да, для каждого теста может потребоваться свое поле. И это поле будет создано под определенный кейс. Например полное поле обычных клеток с одной стрелкой - для тестирования стрелки и тд

2016-12-13 21:32 UTC, VictorKamyshin commented on src/main/java/ru/mail/park/websocket/TestMessage.java
> +public class TestMessage { //отладочное сообщение, которое получено от юзера
Окей, сделаем.

2016-12-13 21:34 UTC, KSolovyev commented on src/main/java/ru/mail/park/mechanics/internal/GameProgressService.java
> +        final Integer x = cellIndex%13;
наверное это должно быть private поле игрового поля, простите за тавтологию

2016-12-13 21:35 UTC, VictorKamyshin commented on src/main/java/ru/mail/park/mechanics/requests/GetPingMessage.java
> +public class GetPingMessage { //пинг от юзера
Без них сокеты просто закрываются по таймауту, если ход второго игрока длится слишком долго.

2016-12-13 21:38 UTC, VictorKamyshin commented on src/main/java/ru/mail/park/mechanics/internal/GameProgressService.java
> +        final Integer x = cellIndex%13;
Тогда как до этого поля доберется метод класса, занимающегося взаимодействием игры и игроков? А он ему нужен, потому что фронт работает с полем в других координатах из-за особенностей графической библиотеки.

2016-12-13 21:42 UTC, VictorKamyshin commented on src/main/java/ru/mail/park/mechanics/game/GameBoard.java
> +        private List<MovementResult> movePirat(Movement piratMove){
Тогда как быть с ситуациями, когда в обычных обстоятельствах движение пирата из этой клетки возможно, но в силу сгенерировавшегося поля / положения в игре, такой ход невозможен? После каждого хода все клетки будут оценивать своих соседей и пересматривать, какие ходы для них допустимы?

2016-12-13 21:49 UTC, VictorKamyshin commented on src/main/java/ru/mail/park/mechanics/GameSession.java
> +public class GameSession {
Сейчас он может сказать, кто противник для выбранного игрок. Но, да, эту функцию тоже можно отдать GameProgressiveService.

2016-12-13 22:03 UTC, VictorKamyshin commented on src/main/java/ru/mail/park/mechanics/game/GameBoard.java
> +        private List<MovementResult> movePirat(Movement piratMove){
Идея была в том, чтобы следовать за бумажным вариантом игры. Каждая клетка это просто каточка, на которой написано, куда из нее можно сходить. А уже игрок, когда берет фигурку в руки, думает, возможен ли ход из клетки А в клетку Б.

2016-12-13 22:15 UTC, KSolovyev commented on src/main/java/ru/mail/park/mechanics/game/GameBoard.java
> +        private List<MovementResult> movePirat(Movement piratMove){
у вас есть кейс, когда клетка на moveOut говорит true, а дальше оказывается, что ход не возможен? Можете привести его?

2016-12-13 22:16 UTC, KSolovyev commented on src/main/java/ru/mail/park/mechanics/requests/GetPingMessage.java
> +public class GetPingMessage { //пинг от юзера
можно увеличить timeout. У вас есть игровые ограничения на длительность хода?

2016-12-13 22:17 UTC, VictorKamyshin commented on src/main/java/ru/mail/park/mechanics/game/GameBoard.java
> +        private List<MovementResult> movePirat(Movement piratMove){
Конкретно сейчас - нет. В перспективе - множество. Пират стоит пустой клетке, все дороги перед ним открыты - но по соседству клетка с крокодилом, в которую он войти не может. Пират подобрал монетку - значит в закрытые клетки он войти уже не сможет. Пират пытается войти в клетку с фортом - но там стоит пират вражеской команды и такой ход запрещен.

2016-12-13 22:18 UTC, KSolovyev commented on src/main/java/ru/mail/park/mechanics/internal/GameProgressService.java
> +        final Integer x = cellIndex%13;
Давайте конкретно: какой класс не может добраться до этой инфы? Просто если у вас фронт шлет координаты в другой системе, то без доски вы не сможете их перевести. Фиксация доски не самый лучший способ. Лучше уж тогда транслировать их при помощи доски

2016-12-13 22:19 UTC, VictorKamyshin commented on src/main/java/ru/mail/park/mechanics/requests/GetPingMessage.java
> +public class GetPingMessage { //пинг от юзера
Нет, и, судя по всему, к защите уже не будет. Значит, нельзя будет сказать "Через N секунд через этот сокет точно пройдет сообщение, или что-то пошло не так".

2016-12-13 22:25 UTC, VictorKamyshin commented on src/main/java/ru/mail/park/mechanics/internal/GameProgressService.java
> +        final Integer x = cellIndex%13;
Класс GameProgressService производит преобразования координат клеток из системы координат фронта в мою и обратно. Для этого ему надо знать размер игровой доски - параметр, который определяется константой класса GameBoard. Я понимаю, что это не лучшая стратегия, но, с другой стороны, это поле - константа и передать его на прямую это не большая беда, мне кажется.

2016-12-13 22:25 UTC, KSolovyev commented on src/main/java/ru/mail/park/mechanics/game/GameBoard.java
> +        private List<MovementResult> movePirat(Movement piratMove){
Можно сделать
```
List<MovementResults> move(long pirateId, Cell fromCell, Cell toCell, @Out List<MovementResults> results) {
        //Возможно проверка "можно ли вообще совершить ход?"
        //....
        if (!fromCell.beforeMoveOut(pirateId, fromCell, toCell, results))
            return results;
        if (!toCell.beforeMoveIn(pirateId, fromCell, toCell, results)) 
            return results;
        if (!fromCell.moveOut(pirateId, fromCell, toCell, results)) 
            return results;
        return toCell.moveIn(pirateId, fromCell, toCell, results);
    }
```

2016-12-13 22:30 UTC, VictorKamyshin commented on src/main/java/ru/mail/park/mechanics/game/GameBoard.java
> +        private List<MovementResult> movePirat(Movement piratMove){
Тогда да, может и получится. Надо попробовать.

2016-12-13 22:31 UTC, KSolovyev commented on src/main/java/ru/mail/park/mechanics/game/GameBoard.java
> +        private List<MovementResult> movePirat(Movement piratMove){
кроме того все это ситуации, которые должен отфильтровать еще фронтенд. Пирату запрещен ход в занятую крепость. А я про ситуацию, когда разрешенный ход приводит к rollback всего хода. Например может ли у вас возникнуть ситуация зацикливания стрелок? Или что делать, когда клетка закрыта, а там стрелка ведущая в занятый форт?

2016-12-13 22:31 UTC, KSolovyev commented on src/main/java/ru/mail/park/mechanics/requests/GetPingMessage.java
> +public class GetPingMessage { //пинг от юзера
ок, тогда оставим пинг

2016-12-13 22:34 UTC, VictorKamyshin commented on src/main/java/ru/mail/park/mechanics/game/GameBoard.java
> +        private List<MovementResult> movePirat(Movement piratMove){
А разве можно в таком вопросе полагаться на то, что их отфильтрует фронтэнд? Ментор по фронту нам говорил, что проверка на бэке должна производиться в любом случае, фронт может ошибаться или слать недостоверную информацию от читеров.
В таком случае пират отмечается как "убитый" и удаляется с доски, ход не откатывается. Можно преставить ситуацию, когда пират входит в неизвестную клетку, видит там крокодила, и возвращается обратно. Но в терминах игры это все равно будет ход, просто не приведший к изменениям на поле.

2016-12-13 22:39 UTC, KSolovyev commented on src/main/java/ru/mail/park/mechanics/game/GameBoard.java
> +        private List<MovementResult> movePirat(Movement piratMove){
Схема работает, просто подумайте, как вы будете решать проблему отката, если игрок, скажем, прошел к конечному полю через несколько стрелок?

2016-12-13 22:44 UTC, VictorKamyshin commented on src/main/java/ru/mail/park/mechanics/game/GameBoard.java
> +        private List<MovementResult> movePirat(Movement piratMove){
Так нет ее, ситуация, когда ход игрока надо полностью откатывать, правилами не предусмотрена. Может быть только что-то на нее похожее визуально. И, по идее, moveResult содержит все перемещения пиратов, которые вызвал этот ход, так что откатить их будет возможно.

2016-12-13 22:47 UTC, KSolovyev commented on src/main/java/ru/mail/park/mechanics/internal/GameProgressService.java
> +        final Integer x = cellIndex%13;
Ладно, сделайте константу. Это сейчас не самая большая проблема

2016-12-16 01:30 UTC, VictorKamyshin commented
1. Закомментированные части кода убрали, комментарии я бы хотел оставить - думаю, так моим товарищам, занимающимся фронтом, будет проще разобраться
2. Добавил тесты на игровую механику
3. Убрал GameSessionService
4. Переработали механику совершения хода
5. Добавили задел под иерархию сообщений о событиях, произошедших во время хода
6. Сервис, который отсылает сообщения пользователю есть в ветке master

2016-12-16 23:11 UTC, KSolovyev requested changes

2016-12-16 23:11 UTC, KSolovyev commented on src/main/java/ru/mail/park/mechanics/game/GameBoard.java
> +                final Integer piratOwner = deadPiratId / 3;
а что это за арифметика с id-шниками? Что такое 3?

2016-12-17 00:10 UTC, VictorKamyshin commented on src/main/java/ru/mail/park/mechanics/game/GameBoard.java
> +                final Integer piratOwner = deadPiratId / 3;
Число пиратов у одного игрока. С одной стороны, айдишник должен однозначно идентифицировать пирата. С другой стороны, каждый игрок имеет массив пиратов из трех элементов и хочется, чтобы айди пирата был индексом в этом массиве. В итоге, на игровой доске айди пирата это (номер пирата у игрока - от 0 до 2) + 3 * (айди игрока в игре). Тогда piratId / 3 - номер игрока. piratId % 3 - номер пирата у игрока.

2016-12-17 00:12 UTC, VictorKamyshin commented on src/main/java/ru/mail/park/mechanics/game/GameBoard.java
> +                final Integer piratOwner = deadPiratId / 3;
Например, в данном случае, deadPiratId - индекс игрока, которому принадлежал убитый пират.

2016-12-17 07:20 UTC, KSolovyev commented on src/main/java/ru/mail/park/mechanics/game/GameBoard.java
> +                final Integer piratOwner = deadPiratId / 3;
В дополнении есть возможность взять еще одного пирата. Что делать будете?

2016-12-17 07:22 UTC, VictorKamyshin commented on src/main/java/ru/mail/park/mechanics/game/GameBoard.java
> +                final Integer piratOwner = deadPiratId / 3;
Страдать :<
По идее, эти айдишники надо заменить на объекты, которые будут хранить номер пирата, номер игрока и, может быть, что-нибудь еще.

2016-12-17 07:27 UTC, KSolovyev commented on src/main/java/ru/mail/park/mechanics/game/GameBoard.java
> +                final Integer piratOwner = deadPiratId / 3;
нет, надо было при создании пиратов засунуть в них ссылку на игрока, а потом всех пиратов вставить в игрока. Сериализовать нужно только аккуратно

2016-12-17 07:30 UTC, KSolovyev commented
давайте на этом закончим, версия рабочая?

2016-12-17 07:33 UTC, merged